### ISSUE TITLE
Question: how can the microphone sensitivity changed in the voicecall profile

### ISSUE THREAD

**Issue by bernhardreiter** [mer-hybris/pulseaudio-modules-droid-jb2q#7]
Hi @jusa,
according to the documentation in the section _Volume control during voicecall_, the usual way to control pulseaudio volume levels does not work. during a voice call. There only seems to be a _sink_input_ in this situation and the sources are all suspended.

On a Sailfish OS (official) Xperia 10 II device  (which uses this pulseaudio module(s)): How can I change the microphone sensitivity (aka source volume) in the voicecall situation? 

It would be nice to have a hint in this section of the documentation.

Background: A number of people have similiar problems see the discussion leading up to https://forum.sailfishos.org/t/audio-quality-during-phone-calls-on-xperia-10-ii/8294/14

**Comment by jusa** [comment]
Microphone sensitivity is something that cannot be changed dynamically during cellular call. The reason for this is how the call implementation is done in Android BSP. During voice call the whole process is done behind the curtain, and we only have access to setup the call etc. During voice call audio is not processed in main CPU side, so we don't have any direct control on the audio streams coming out or recorded. Output volume is set through a specific API, and that is the reason there exists this virtual stream during a call - changes done to that are forwarded to the voice volume API.

In Xperia 10 II sensitivities and all values are defined in `/etc/vendor/mixer_paths.xml` (a file which is read by the audio HAL), but how everything maps out is difficult to figure out or modify without having specs for the chip.

**Comment by bernhardreiter** [comment]
> Microphone sensitivity is something that cannot be changed dynamically during cellular call.

To solve the issue a few people and I have (in my understanding) it would be fine to permanently reduce the microphone sensitivity. I did this via pulse audio for app calls and recorder and it was a clear improvement. 

> In Xperia 10 II sensitivities and all values are defined in /etc/vendor/mixer_paths.xml (a file which is read by the audio HAL), but how everything maps out is difficult to figure out or modify without having specs for the chip.

Thanks a lot for this important hint! As voice calls are seriously affected by the current situation with my `Xperia 10 II` running with sfos I might as well see if I can play with a few values in this file.

 On a related account: Any idea what that `limit_volume` option to `/etc/pulse/xpolicy.conf` might do that if reportedly has fixed the issue for some users?
